name: flup_youtube_backend
description: A sample command-line application.
version: 1.0.2

environment:
  sdk: ^3.0.5

dependencies:
  shelf: ^1.4.1
  uuid: ^3.0.7
  youtube_explode_dart: ^2.0.2
  karaoke_request_api:
    hosted: https://dart.pkg.jetbrains.space/flup/p/main/flup/
    version: ^1.8.4
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
