name: flup_youtube_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shelf: ^1.4.1
  uuid: ^3.0.7
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
