name: flup_youtube_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  shelf: ^1.4.1
  uuid: ^3.0.7
  youtube_explode_dart: ^2.0.2
  karaoke_request_api:
    git:
      url: https://github.com/felipeuematsu/karaoke_request_api
      ref: 1.3.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
